oslo_city_bikes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: bzyexbi-oq9720
      user: ANNMAK2019
      authenticator: externalbrowser
      role: ACCOUNTADMIN
      database: OSLO_CITY_BIKES
      warehouse: COMPUTE_WH
      schema: DBT_DEV
      threads: 4
      client_session_keep_alive: False
