-- after Snowflake account change

CREATE DATABASE OSLO_CITY_BIKES;

CREATE SCHEMA OSLO_CITY_BIKES.STAGE;

CREATE STAGE OSLO_CITY_BIKES.STAGE.OSLO_BIKES_STAGE;

CREATE OR REPLACE TABLE OSLO_CITY_BIKES.STAGE.BIKES_STATIONS (
    STARTED_AT TIMESTAMP_NTZ(9),
    ENDED_AT TIMESTAMP_NTZ(9),
    DURATION NUMBER(38,0),
    START_STATION_ID NUMBER(38,0),
    START_STATION_NAME VARCHAR(16777216),
    START_STATION_DESCRIPTION VARCHAR(16777216),
    START_STATION_LATITUDE FLOAT,
    START_STATION_LONGITUDE FLOAT,
    END_STATION_ID NUMBER(38,0),
    END_STATION_NAME VARCHAR(16777216),
    END_STATION_DESCRIPTION VARCHAR(16777216),
    END_STATION_LATITUDE FLOAT,
    END_STATION_LONGITUDE FLOAT
);